# Generated by Django 4.0.4 on 2022-06-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=165)),
                ('slug', models.SlugField()),
                ('condition_value', models.IntegerField()),
                ('condition_unit', models.CharField(max_length=65)),
                ('price', models.IntegerField()),
                ('price_unit', models.CharField(max_length=65)),
                ('sneaker_description', models.TextField()),
                ('sneaker_description_is_html', models.BooleanField(default=False)),  # noqa: E501
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='sneakers/covers/%Y/%m/%d/')),  # noqa: E501
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),  # noqa: E501
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sneakers.category')),  # noqa: E501
            ],
        ),
    ]
