# Generated by Django 4.0.4 on 2022-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
