# Generated by Django 4.0.4 on 2022-09-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_alter_sneaker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sneakers.category'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='condition_unit',
            field=models.CharField(default='/10', max_length=65),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price_unit',
            field=models.CharField(default='R$', max_length=65),
        ),
    ]
